version: "3"

networks:
    # internal database for service communication
    # external communication must use `default` network
    tradewars:
        driver: bridge
        internal: true

services:

    #
    # watchtower restarts containers when new tags are detected
    #

    watchtower:
        image: v2tec/watchtower
        command:
        - "-label-enable"
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock


    # -
    # databases
    # -

    mongodb:
        image: 'mongo:3.4'
        command: mongod
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USER}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASS}'
            MONGO_INITDB_DATABASE: '${MONGODB_NAME}'
        volumes:
            - '${DATA_DIR}/${COMPOSE_PROJECT_NAME}/mongodb:/data/db'
        networks:
            - tradewars
        labels:
            - traefik.enable=false


    # -
    # tradewars stack
    # -

    gamemode:
        image: southclaws/tw-gamemode:${VERSION}
        networks:
            - default
            - tradewars
        labels:
            - 'com.centurylinklabs.watchtower.enable="true"'

    warehouse:
        image: southclaws/tw-warehouse:${VERSION}
        environment:
            WAREHOUSE_TEMPORARY: "false"
            WAREHOUSE_BIND: "0.0.0.0:7788"
            WAREHOUSE_AUTH: '${WAREHOUSE_AUTH}'
            WAREHOUSE_MONGO_HOST: "mongodb"
            WAREHOUSE_MONGO_PORT: "27017"
            WAREHOUSE_MONGO_NAME: '${MONGODB_NAME}'
            WAREHOUSE_MONGO_USER: '${MONGODB_USER}'
            WAREHOUSE_MONGO_PASS: '${MONGODB_PASS}'
        ports:
            - '7788:7788'
        networks:
            - tradewars
        labels:
            - 'com.centurylinklabs.watchtower.enable="true"'
